#!/bin/bash

apt-get update
apt-get upgrade -y
apt-get install -y parted git python3 python3-pip nodejs npm make curl ca-certificates
curl -sSL https://install.python-poetry.org | python3 -
git clone https://github.com/OpenDevin/OpenDevin
cd OpenDevin
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
mamba install python=3.11
mamba install conda-forge::nodejs
mamba install conda-forge::poetry
make build
make setup-config
make run
